
title: Meu curriculo
url: 'http://allcriativa.com.br'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Allan Segalote
tagline: Estudante
pic: allan.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: allan@segalote.com.br
phone: (21) 99559-8709
website: allcriativa.com.br #do not add http://
linkedin: allansegalote
github: allansegalote
twitter: '@allansegalote'


# Tracker
analytics: UA0000000
#Update all the sections by editing the files inside _includes folder.
